FROM node:22.14.0
WORKDIR /app
COPY ./frontend/package*.json ./
RUN rm -rf node_modules package-lock.json # 削除
RUN npm install # 再度インストール
COPY ./frontend .
EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]