FROM ruby:3.4.3

# 必要パッケージ
RUN apt-get update -qq && apt-get install -y nodejs postgresql-client

# 作業ディレクトリを /app に
WORKDIR /app

# Gemfileをコピーしてbundle install
COPY backend/Gemfile /app/Gemfile
COPY backend/Gemfile.lock /app/Gemfile.lock
RUN bundle install

# アプリ全体をコピー
COPY backend /app
